
export const SET_BEER_COLLECTION = 'SET_BEER_COLLECTION'

export const SORT_BY_WORD_UP = 'SORT_BY_WORD_UP'
export const SORT_BY_WORD_DOWN = 'SORT_BY_WORD_DOWN'

export const SORT_BY_OVERALL_UP = 'SORT_BY_OVERALL_UP'
export const SORT_BY_OVERALL_DOWN = 'SORT_BY_OVERALL_DOWN'

export const SEARCH_FOR_BEER = 'SEARCH_FOR_BEER'


export const SELECTED_MENU_OPTIONS = "SELECTED_MENU_OPTIONS"

